.TH COP4DISASS L "22 August 2016"
.UC 4
.SH NAME
cop4disas \- disassemble COP4 executable
.SH SYNOPSIS
.B cop4disas
[ \-l] [ \-a address] file
.SH DESCRIPTION
.I cop4disas
will disassemble a COP4 executable.
.PP
File
.IR file
contains binary data, which cop4disas will interpet
as COP4 machine language code.
.PP
By default, the starting addres is 0x000, but this can be changed
with the -a option (e.g. cop4disas -a 0x80 file).
.PP
The -a option specifies a new starting address.
.PP
The -l flag will produce a long listing with adrresses and binary opcodes.
.SH "SEE ALSO"
cop4disass produces output compatible with the AS macro assembler (http://john.ccac.rwth-aachen.de:8000/as)
